#!/bin/bash

echo "Leaving $(pushd .)"
cd scripts/
echo ""
echo "In $(pwd): Building js files"
browserify source.js -d | minify --js > main.min.js
cd ../styles/
echo "In $(pwd): Building css files"
minify main.css > main.min.css
echo ""
echo "returned to $(popd)"
