#!/bin/bash

echo "Leaving $(pwd)"
cd scripts/
echo ""
echo "In $(pwd): Building js files"
browserify source.js -d | minify --js > main.min.js
#browserify source.js -d -o main.js
#cd ../styles/
#echo "In $(pwd): Building css files"
#minify main.css > main.min.css
echo ""
echo "returned to $(pwd)"
